# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fe2e1f4101f085b70221379d47e93d9c155f39f5dae695e6e657348bf2605338ce3a00bc0c9200c5a69517cb2d4ffabc7daef4d546cc26ab956b38246ee638e

test:
  secret_key_base: 11db6979a169a597ec25018fd8bedc01e8fa6f878011c327ffc89b781cb9d25481521ff80bf1cdf01e6771efa978e93109cd0d7c0152ca938697b04b48bb7ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
